# Generated by Django 3.2 on 2021-04-11 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AGTHolsterStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='AGTPlaketteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Fahrzeug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FahrzeugTyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PAStandort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standort', models.CharField(max_length=10)),
                ('fahrzeugID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGTCheckController.fahrzeug')),
            ],
        ),
        migrations.CreateModel(
            name='Pruefer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('vorname', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TotmannwarnerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Verwaltung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pruefung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paNummer', models.IntegerField()),
                ('druck', models.IntegerField()),
                ('druckabfall', models.IntegerField()),
                ('restdruckwarneinrichtung', models.BooleanField()),
                ('flammschutzhaube', models.BooleanField()),
                ('pruefungOK', models.BooleanField()),
                ('datum', models.DateTimeField(auto_now=True)),
                ('agtHolsterStatusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGTCheckController.agtholsterstatus')),
                ('agtPlaketteStatusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGTCheckController.agtplakettestatus')),
                ('paStandortID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGTCheckController.pastandort')),
                ('prueferID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGTCheckController.pruefer')),
                ('totmannwarnerStatusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGTCheckController.totmannwarnerstatus')),
            ],
        ),
        migrations.AddField(
            model_name='fahrzeug',
            name='opta1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGTCheckController.organisation'),
        ),
        migrations.AddField(
            model_name='fahrzeug',
            name='opta2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGTCheckController.verwaltung'),
        ),
        migrations.AddField(
            model_name='fahrzeug',
            name='opta3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGTCheckController.fahrzeugtyp'),
        ),
    ]
